name = "PBouffardJuliaPackageRegistry"
uuid = "c6f79cb6-679d-4a68-bf70-9ce25d409fb1"
repo = "git@github.com:pbouffard/PBouffardJuliaPackageRegistry.git"
description = "My personal (public) registry"

[packages]
4542c7b1-ea73-42e5-9a85-c29583659a5a = { name = "PlotJuggler", path = "P/PlotJuggler" }
